# Generated by Django 4.2.11 on 2026-04-29 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0002_alter_exercise_options_alter_musclegroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('mission_type', models.CharField(choices=[('daily', 'Diaria'), ('weekly', 'Semanal')], max_length=10)),
                ('condition_type', models.CharField(choices=[('workout_count', 'Sesiones completadas'), ('xp_gained', 'XP acumulada en el dia'), ('muscle_count', 'Musculos distintos entrenados'), ('streak_days', 'Dias de racha'), ('exercise_count', 'Ejercicios en una sesion')], max_length=20)),
                ('condition_value', models.PositiveIntegerField()),
                ('xp_reward', models.PositiveIntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Facil'), ('medium', 'Media'), ('hard', 'Dificil')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('condition_muscle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='exercises.musclegroup')),
            ],
            options={
                'ordering': ['mission_type', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='UserMission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_date', models.DateField()),
                ('current_progress', models.PositiveIntegerField(default=0)),
                ('target_value', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Activa'), ('completed', 'Completada'), ('expired', 'Expirada')], default='active', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_missions', to='missions.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_missions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_date', 'status'],
            },
        ),
    ]
