# Generated by Django 4.2.11 on 2026-04-04 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='musclegroup',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='order',
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('strength', 'Fuerza'), ('cardio', 'Cardio')], default='strength', max_length=10),
        ),
        migrations.AddField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_groups',
            field=models.ManyToManyField(blank=True, related_name='exercises', through='exercises.ExerciseMuscle', to='exercises.musclegroup'),
        ),
        migrations.AlterModelTable(
            name='musclegroup',
            table='muscle_groups',
        ),
    ]
