# Generated by Django 4.2.11 on 2026-04-29 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0002_alter_exercise_options_alter_musclegroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('condition_type', models.CharField(choices=[('streak', 'Racha de días consecutivos'), ('level', 'Nivel general alcanzado'), ('total_xp', 'XP total acumulada'), ('muscle_level', 'Nivel en músculo específico'), ('workout_count', 'Sesiones completadas'), ('mission_count', 'Misiones completadas')], max_length=20)),
                ('condition_value', models.PositiveIntegerField()),
                ('xp_reward', models.PositiveIntegerField()),
                ('rarity', models.CharField(choices=[('common', 'Común'), ('uncommon', 'Poco común'), ('rare', 'Raro'), ('epic', 'Épico'), ('legendary', 'Legendario')], max_length=10)),
                ('badge_icon', models.CharField(max_length=100)),
                ('condition_muscle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='exercises.musclegroup')),
            ],
            options={
                'ordering': ['rarity', 'condition_value'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='achievements.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
